Use EnvironmentHelper for database URL and install variables.
shopware/production pull request #133
Opened 2022-01-28 07:21 UTC by AndreasA

Fixes: https://github.com/shopware/production/issues/132

2022-01-28 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopware/production?pullRequest=133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopware/production?pullRequest=133) before we can accept your contribution.<br/><hr/>**Andreas Allacher** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopware/production?pullRequest=133) it.</sub>

2022-01-28 07:26 UTC, keulinho requested changes

2022-01-28 07:26 UTC, keulinho commented on bin/console
> +    if (null === $install) {
```suggestion
    if (EnvironmentHelper::hasVariable('INSTALL')) {
```

2022-01-28 07:26 UTC, keulinho commented on src/Kernel.php
> +        if (null !== $install || $url === self::PLACEHOLDER_DATABASE_URL) {
```suggestion
        if (EnvironmentHelper::hasVariable('INSTALL') || $url === self::PLACEHOLDER_DATABASE_URL) {
```

2022-01-28 07:34 UTC, AndreasA commented on bin/console
> +    if (null === $install) {
done

2022-01-28 07:34 UTC, AndreasA commented on src/Kernel.php
> +        if (null !== $install || $url === self::PLACEHOLDER_DATABASE_URL) {
done

2022-01-28 07:39 UTC, keulinho approved these changes

2022-01-28 07:40 UTC, AndreasA commented
@keulinho can you re-check I also added the changes to `bin/ci` now. as it uses nearly the same logic as `bin/console`

2022-01-28 08:05 UTC, keulinho approved these changes

2022-01-31 06:15 UTC, shyim approved these changes

2022-01-31 06:25 UTC, shyim commented
Hey,

the PR looks good. We are currently in releasing new version and don't merge new things into the template. I will import it when the new version is released.

2022-02-10 11:48 UTC, closed without merging

2022-02-10 12:22 UTC, keulinho commented
Hey @AndreasA thanks for your contribution! :tada: :blue_heart: